language: php

php:
  - 5.3 # test does not work because of libxml_set_external_entity_loader()
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.3

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

after_script:
  - php vendor/bin/coveralls -v

